---
title: "Lab 1"
author: "Emily Mingus, Aden Bhagwat, Erick Njue"
date: "2025-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Installing edld652 data package
#install.packages("remotes")
#library(remotes)
#remotes::install_github("datalorax/edld652", force = TRUE)
#library(edld652)
#list_datasets()

#acgd <- get_data("EDFacts_acgr_lea_2011_2019")

#set_key('emilyabcdef')

```

```{r}
library(edld652)
library(tidyverse)

#set_key('aden1234')

#list_datasets()
#Sys.unsetenv("AZURE_SAS_TOKEN")  # Clear any existing token
# Set your new SAS token
#Sys.setenv(AZURE_SAS_TOKEN = "aden1234")

acgd <- get_data("EDFacts_acgr_lea_2011_2019")


acgdd <- get_documentation("EDFacts_acgr_lea_2011_2019")

#list_datasets()
#NOT WORKING

```

```{r}
library(here)
library(rio)
library(ggplot2)
df<-import(here("data/rstats_tweets.rds"))

df %>% 
  ggplot(aes(x= display_text_width))+
  geom_histogram(bins=30)

df %>% 
  ggplot(aes(x= display_text_width))+
  geom_histogram(bins=10)

df %>% 
  ggplot(aes(x= display_text_width))+
  geom_histogram(bins=100)

df %>% 
  ggplot(aes(x= display_text_width))+
  geom_histogram(bins=500)

```

We are using 30 bins which is what R automatically selects, we think this gives the clearest pattern without being overwhelming. 

```{r}
df$text

n_plot <- sum(grepl("plot", tolower(df$text))) 

n_plot/nrow(df)
  
```

6.8% of the posts contain the word plot

```{r}
library(tidytext)
df_text <- df %>% 
  unnest_tokens(word, description)


df_text

df_text %>% 
  anti_join(stop_words) %>%
  filter(!word %in% c("t.co", "https", "http", "rt", "rstats")) %>%
  count(word, sort = TRUE) %>% 
  mutate(word = reorder(word, n)) %>% # make y-axis ordered by n
  slice(1:15) %>% # select only the first 15 rows
  ggplot(aes(n, word)) +
    geom_col(fill = "cornflowerblue")+
  theme_minimal()+
  labs(x="Count", y="Word", title="Word frequencies in posts", subtitle= "Top 15 words displayed", caption= "Data from Mike Kearny, distributed via #tidytuesday")


```

